# Generated by Django 5.0.14 on 2026-09-06 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_unnati_extensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('instant', 'Instant Booking'), ('scheduled', 'Scheduled Booking'), ('collective', 'Collective Multi-Worker Booking')], default='instant', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('searching', 'Searching For Worker (REQUESTED)'), ('MATCHING', 'Matching Workers'), ('accepted', 'Worker Accepted'), ('SCHEDULED', 'Scheduled in Advance'), ('on_the_way', 'Worker On The Way (WORKER_ARRIVING)'), ('arrived', 'Worker Arrived'), ('verified', 'QR / Geofence Verified'), ('inspection', 'Inspection'), ('repair_started', 'Repair Started (IN_PROGRESS)'), ('repair_completed', 'Repair Completed'), ('waiting_approval', 'Waiting For Customer Approval'), ('WAITING_FOR_CASH_CONFIRMATION', 'Waiting For Cash Confirmation'), ('ready_to_complete', 'Ready To Complete (PAYMENT_RELEASED)'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='searching', max_length=50),
        ),
        migrations.CreateModel(
            name='BookingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=50)),
                ('to_status', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='bookings.booking')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingWorkerAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cooperative_dividend_share', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('arrived', 'Arrived'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('disputed', 'Disputed')], default='assigned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_allocations', to='bookings.booking')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperative_allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('booking', 'worker')},
            },
        ),
    ]
