# Generated by Django 5.0.14 on 2026-09-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_alter_booking_booking_type_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='arrival_pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='arrival_pin_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='arrival_pin_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingrejection',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('searching', 'Searching For Worker (REQUESTED)'), ('requested', 'Requested'), ('MATCHING', 'Matching Workers'), ('accepted', 'Worker Accepted'), ('SCHEDULED', 'Scheduled in Advance'), ('scheduled', 'Scheduled'), ('on_the_way', 'Worker On The Way (WORKER_ARRIVING)'), ('arrived', 'Worker Arrived'), ('verified', 'QR / Arrival PIN / Geofence Verified'), ('inspection', 'Inspection'), ('repair_started', 'Repair Started (IN_PROGRESS)'), ('in_progress', 'In Progress'), ('repair_completed', 'Repair Completed'), ('waiting_approval', 'Waiting For Customer Approval'), ('WAITING_FOR_CASH_CONFIRMATION', 'Waiting For Cash Confirmation'), ('ready_to_complete', 'Ready To Complete (PAYMENT_RELEASED)'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='searching', max_length=50),
        ),
    ]
