# Generated by Django 5.0.14 on 2026-09-06 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_announcement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(blank=True, default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='channel_delivery_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivered_channel',
            field=models.CharField(blank=True, default='IN_APP', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='language',
            field=models.CharField(blank=True, default='hi', max_length=10),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled_channels', models.JSONField(blank=True, default=list)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.CharField(default='22:00', max_length=10)),
                ('quiet_hours_end', models.CharField(default='07:00', max_length=10)),
                ('preferred_language', models.CharField(default='hi', max_length=10)),
                ('opportunity_radius_km', models.FloatField(default=10.0)),
                ('urgent_bypasses_quiet_hours', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.IntegerField(blank=True, null=True)),
                ('service_title', models.CharField(max_length=150)),
                ('coarse_locality', models.CharField(max_length=150)),
                ('coarse_distance_km', models.FloatField(default=0.0)),
                ('estimated_payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ACCEPTED', 'Accepted'), ('DISMISSED', 'Dismissed'), ('EXPIRED', 'Expired')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
